# Generated by Django 5.2.8 on 2025-11-16 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iso_code', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date of the sample.', verbose_name='Date')),
                ('name', models.CharField(help_text='The name of the sample.', max_length=30, verbose_name='Name')),
                ('email', models.EmailField(blank=True, help_text='The email of the sample.', max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='The phone of the sample.', max_length=20, null=True, verbose_name='Phone')),
                ('description', models.TextField(blank=True, help_text='The description of the sample.', null=True, verbose_name='Description')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Draft'), (2, 'Started'), (3, 'Finished'), (4, 'Closed')], default=1, help_text='The status of the sample.', null=True, verbose_name='Status')),
                ('active', models.BooleanField(blank=True, default=False, help_text='The active status of the sample.', null=True, verbose_name='Active')),
                ('integer', models.IntegerField(blank=True, help_text='The integer value of the sample.', null=True, verbose_name='Integer')),
                ('decimal', models.DecimalField(blank=True, decimal_places=2, help_text='The decimal value of the sample.', max_digits=10, null=True, verbose_name='Decimal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, help_text='The country associated with the sample.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='sampleapp.country', verbose_name='Country')),
                ('user', models.ForeignKey(help_text='The user associated with the sample.', on_delete=django.db.models.deletion.CASCADE, related_name='samples', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Sample',
                'verbose_name_plural': 'Samples',
            },
        ),
    ]
